=== luhao007/WoW-Classic-Addons/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.github.com/luhao007"
           xmlns="https://www.github.com/luhao007"
           elementFormDefault="unqualified">

    <xs:element name="AddonConfig">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="Addon" type="Addon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Addon">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"  nillable="false"/>
            <xs:element name="Title-en" type="xs:string" minOccurs="0"/>
            <xs:element name="Notes" type="xs:string" minOccurs="0"/>
            <xs:element name="Category" type="xs:string" nillable="false"/>
            <xs:element name="SubAddons" minOccurs="0">
                <xs:complexType>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element name="SubAddon" type="SubAddon"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="SubAddon">
        <xs:sequence>
            <xs:element name="Title" type="xs:string" nillable="false"/>
            <xs:element name="TitleExtra" type="xs:string" minOccurs="0"/>
            <xs:element name="Notes" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== luhao007/WoW-Classic-Addons/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<AddonConfig xmlns="https://www.github.com/luhao007"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="https://www.github.com/luhao007 addon.xsd">
	<Addon name="!!Libs">
		<Title>|cFF7FFF7FAce核心库|r |cFFFF0000必须加载|r</Title>
		<Category>基础库</Category>
	</Addon>
	<Addon name="+Wowhead_Looter">
		<Title>Wowhead数据采集</Title>
		<Notes>收集各种游戏内数据并上传Wowhead</Notes>
		<Category>辅助</Category>
	</Addon>
	<Addon name="ACP">
		<Title>插件管理</Title>
		<Category>基础库</Category>
	</Addon>
	<Addon name="alaCalendar">
		<Title>副本日历</Title>
		<Category>界面</Category>
	</Addon>
	<Addon name="alaTalentEmu">
		<Title>天赋模拟器</Title>
		<Category>战斗</Category>
	</Addon>
	<Addon name="AngryKeystones">
		<Title>钥石助手</Title>
		<Category>副本</Category>
	</Addon>
	<Addon name="ATT-Classic">
		<Title>收集控助手</Title>
		<Notes>追踪账号完成度，提示诸如任务、飞行点、配方等各个分类的收集和完成情况</Notes>
		<Category>收藏</Category>
	</Addon>
	<Addon name="AchievementsReminder">
		<Title>成就提醒</Title>
		<Notes>提示当前区域可完成的成就以及完成方法</Notes>
		<Category>收藏</Category>
	</Addon>
	<Addon name="AdvancedInterfaceOptions">
		<Title>高级界面设置</Title>
		<Notes>可以修改各种隐藏参数，包括隐藏的内部CVar参数</Notes>
		<Category>功能</Category>
	</Addon>
	<Addon name="AllTheThings">
		<Title>收集控助手</Title>
		<Notes>追踪账号完成度，提示诸如任务、飞行点、配方等各个分类的收集和完成情况</Notes>
		<Category>收藏</Category>
	</Addon>
	<Addon name="Atlas">
		<Title>副本地图</Title>
		<Category>副本</Category>
		<SubAddons>
			<SubAddon name="Atlas_Arena">
				<Title>竞技场</Title>
			</SubAddon>
			<SubAddon name="Atlas_BattleforAzeroth">
				<Title>争霸艾泽拉斯</Title>
			</SubAddon>
			<SubAddon name="Atlas_Battlegrounds">
				<Title>战场</Title>
			</SubAddon>
			<SubAddon name="Atlas_BurningCrusade">
				<Title>燃烧的远征</Title>
			</SubAddon>
			<SubAddon name="Atlas_Cataclysm">
				<Title>大地的裂变</Title>
			</SubAddon>
			<SubAddon name="Atlas_ClassicWoW">
				<Title>经典旧世</Title>
			</SubAddon>
			<SubAddon name="Atlas_ClassOrderHalls">
				<Title>职业大厅</Title>
			</SubAddon>
			<SubAddon name="Atlas_DungeonLocs">
				<Title>副本位置</Title>
			</SubAddon>
			<SubAddon name="Atlas_Legion">
				<Title>军团再临</Title>
			</SubAddon>
			<SubAddon name="Atlas_MistsofPandaria">
				<Title>熊猫人之迷</Title>
			</SubAddon>
			<SubAddon name="Atlas_OutdoorRaids">
				<Title>户外首领</Title>
			</SubAddon>
			<SubAddon name="Atlas_Scenarios">
				<Title>场景战役</Title>
			</SubAddon>
			<SubAddon name="Atlas_Transportation">
				<Title>交通</Title>
			</SubAddon>
			<SubAddon name="Atlas_WarlordsofDraenor">
				<Title>德拉诺之王</Title>
			</SubAddon>
			<SubAddon name="Atlas_WorldEvents">
				<Title>世界事件</Title>
			</SubAddon>
			<SubAddon name="Atlas_WrathoftheLichKing">
				<Title>巫妖王之怒</Title>
			</SubAddon>
			<SubAddon name="AtlasMajorCitiesEnhanced">
				<Title>主城地图</Title>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="AtlasLoot">
		<Title>副本掉落</Title>
		<Notes>显示首领可能掉落的物品</Notes>
		<Category>副本</Category>
		<SubAddons>
			<SubAddon name="AtlasLoot_BattleforAzeroth">
				<Title>争霸艾泽拉斯</Title>
				<Notes>AtlasLoot 争霸艾泽拉斯副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_BurningCrusade">
				<Title>燃烧的远征</Title>
				<Notes>AtlasLoot 燃烧的远征副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Cataclysm">
				<Title>大地的裂变</Title>
				<Notes>AtlasLoot 大地的裂变副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Classic">
				<Title>经典旧世</Title>
				<Notes>AtlasLoot 经典旧世副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Collections">
				<Title>套装</Title>
				<Notes>AtlasLoot 套装列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Crafting">
				<Title>专业制作</Title>
				<Notes>AtlasLoot 专业制作物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Factions">
				<Title>阵营</Title>
				<Notes>AtlasLoot 阵营物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Legion">
				<Title>军团再临</Title>
				<Notes>AtlasLoot 军团再临副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_MistsofPandaria">
				<Title>熊猫人之谜</Title>
				<Notes>AtlasLoot 熊猫人之谜副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_Options">
				<Title>设置</Title>
				<Notes>AtlasLoot 选项模块</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_PvP">
				<Title>PVP</Title>
				<Notes>AtlasLoot PVP物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_WarlordsofDraenor">
				<Title>德拉诺之王</Title>
				<Notes>AtlasLoot 德拉诺之王副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_WorldEvents">
				<Title>世界事件</Title>
				<Notes>AtlasLoot 世界事件物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLoot_WrathoftheLichKing">
				<Title>巫妖王之怒</Title>
				<Notes>AtlasLoot 巫妖王之怒副本掉落列表</Notes>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="AtlasLootClassic">
		<Title>副本掉落</Title>
		<Notes>显示首领可能掉落的物品</Notes>
		<Category>副本</Category>
		<SubAddons>
			<SubAddon name="AtlasLootClassic_Collections">
				<Title>套装</Title>
				<Notes>AtlasLoot 套装列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_Crafting">
				<Title>专业制作</Title>
				<Notes>AtlasLoot 专业制作物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_Data">
				<Title>数据</Title>
				<Notes>AtlasLoot 物品数据</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_DungeonsAndRaids">
				<Title>地下城和团队</Title>
				<Notes>AtlasLoot 地下城和团队副本掉落列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_Factions">
				<Title>阵营</Title>
				<Notes>AtlasLoot 阵营物品列表</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_Maps">
				<Title>地图</Title>
				<Notes>AtlasLoot 地图模块</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_Options">
				<Title>设置</Title>
				<Notes>AtlasLoot 选项模块</Notes>
			</SubAddon>
			<SubAddon name="AtlasLootClassic_PvP">
				<Title>PVP</Title>
				<Notes>AtlasLoot PVP物品列表</Notes>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="AtlasQuest">
		<Title>副本任务</Title>
		<Notes>副本任务列表</Notes>
		<Category>副本</Category>
	</Addon>
	<Addon name="Auc-Advanced">
		<Title>拍卖助手</Title>
		<Notes>拍卖助手可以帮助玩家扫描并追踪各个物品的拍卖价格，并且提供各种进阶扫描，如拍卖叫小于买店价的商品</Notes>
		<Category>物品</Category>
		<SubAddons>
			<SubAddon name="!Swatter">
				<Title>错误提示</Title>
				<Notes>增强错误提示，将错误显示在弹出窗口中</Notes>
			</SubAddon>
			<SubAddon name="Auc-Filter-Basic">
				<Title>基础过滤条件</Title>
				<Notes>提供基础过滤条件，比如最低装等，最低价格等等</Notes>
			</SubAddon>
			<SubAddon name="Auc-ScanData">
				<Title>数据扫描</Title>
				<Notes>让拍卖助手支持延时扫描功能，用来分页扫描拍卖行的大量数据</Notes>
			</SubAddon>
			<SubAddon name="Auc-Stat-Histogram">
				<Title>统计</Title>
				<TitleExtra>直方图</TitleExtra>
				<Notes>让拍卖助手可以用直方图的形式展示统计数据</Notes>
			</SubAddon>
			<SubAddon name="Auc-Stat-Purchased">
				<Title>统计</Title>
				<TitleExtra>已售物品</TitleExtra>
				<Notes>让拍卖助手用来推测已售商品（还未到原定拍卖时间就已下架）</Notes>
			</SubAddon>
			<SubAddon name="Auc-Stat-Simple">
				<Title>统计</Title>
				<TitleExtra>简单统计</TitleExtra>
				<Notes>提供1/3/7/14天指数移动平均的统计数据</Notes>
			</SubAddon>
			<SubAddon name="Auc-Stat-StdDev">
				<Title>统计</Title>
				<TitleExtra>标准差</TitleExtra>
				<Notes>让拍卖助手通过标准差来提供参考拍卖价格</Notes>
			</SubAddon>
			<SubAddon name="Auc-Stat-iLevel">
				<Title>统计</Title>
				<TitleExtra>装备等级</TitleExtra>
				<Notes>让拍卖助手通过装备类型，装备等级等一系列参数来合并统计数据</Notes>
			</SubAddon>
			<SubAddon name="Auc-Util-FixAH">
				<Title>功能</Title>
				<TitleExtra>固定搜索页面</TitleExtra>
				<Notes>让拍卖行每次搜索时都固定显示新物品，来避免物品重复出现的问题</Notes>
			</SubAddon>
			<SubAddon name="BeanCounter">
				<Title>物品会计师</Title>
				<Notes>存储物品购买销售记录</Notes>
			</SubAddon>
			<SubAddon name="Enchantrix">
				<Title>附魔助手</Title>
				<Notes>提示物品分解后可能得到的材料</Notes>
			</SubAddon>
			<SubAddon name="Enchantrix-Barker">
				<Title>附魔助手</Title>
				<TitleExtra>叫卖</TitleExtra>
				<Notes>将可以进行的附魔价格发送到交易频道</Notes>
			</SubAddon>
			<SubAddon name="SlideBar">
				<Title>侧边滑动栏</Title>
				<Notes>在屏幕边提供一个可以滑动栏来显示小地图图标</Notes>
			</SubAddon>
			<SubAddon name="Stubby">
				<Title>调用助手</Title>
				<Notes>让Auctioneer各种子插件可以需要时自动加载</Notes>
			</SubAddon>
			<SubAddon name="Informant">
				<Title>物品信息</Title>
				<Notes>在鼠标提示中提供更详细的物品信息，如商店购买价和销售价等</Notes>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="Bagnon">
		<Title>背包整合</Title>
		<Notes>将背包整合成一个窗口</Notes>
		<Category>物品</Category>
		<SubAddons>
			<SubAddon name="BagBrother">
				<Title>助手</Title>
				<Notes>记录背包和银行中的物品</Notes>
			</SubAddon>
			<SubAddon name="Bagnon_Config">
				<Title>设置</Title>
				<Notes>Bagnon设置模块</Notes>
			</SubAddon>
			<SubAddon name="Bagnon_GuildBank">
				<Title>公会银行</Title>
				<Notes>Bagnon公会银行模块</Notes>
			</SubAddon>
			<SubAddon name="Bagnon_VoidStorage">
				<Title>虚空仓库</Title>
				<Notes>Bagnon虚空仓库模块</Notes>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="BattlePetBreedID">
		<Title>战斗宠物品种</Title>
		<Notes>显示战斗宠物的品种（如速度型）</Notes>
		<Category>收藏</Category>
	</Addon>
	<Addon name="BlizzMove">
		<Title>窗口移动</Title>
		<Notes>移动内置的各种窗口</Notes>
		<Category>界面</Category>
		<SubAddons>
			<SubAddon name="BlizzMove_Debug">
				<Title>错误调试</Title>
				<Notes>获取报错信息以用于调试</Notes>
			</SubAddon>
		</SubAddons>
	</Addon>
	<Addon name="BtWQuests">
		<Title>任务流程图</Title>
		<Notes>将所有任务的前置任务和后续任务用流程图显示出来</Notes>
		<Category>任务</Category>
		<SubAddons>
			<SubAddon name="BtWObjectiveFilter">
				<Title>追踪过滤</Title>
				<Notes>在任务和副本目标等追踪界面中添加一个过滤器，来关闭不想看到的追踪</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsBattleForAzeroth">
				<Title>争霸艾泽拉斯</Title>
				<Notes>BtWQuests 争霸艾泽拉斯模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsCataclysm">
				<Title>大灾变</Title>
				<Notes>BtWQuests 大灾变模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsLegion">
				<Title>军团再临</Title>
				<Notes>BtWQuests 军团再临模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsLegion">
				<Title>军团再临</Title>
				<Notes>BtWQuests 军团再临模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsMistsOfPandaria">
				<Title>熊猫人之谜</Title>
				<Notes>BtWQuests 熊猫人之谜模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsShadowlands">
				<Title>暗影国度</Title>
				<Notes>BtWQuests 暗影国度模块</Notes>
			</SubAddon>
			<SubAddon name="BtWQuestsTheBurningCrusade">
				<Title>燃烧的远征</Title>
